### ISSUE TITLE
Link to vvo/lazyload

### ISSUE THREAD

**Issue by gmetais** [francetv/ftv-angular-lazyload#1]
Hi there!

This project depends on this other project: https://github.com/vvo/lazyload which is currently commited into https://github.com/francetv/ftv-angular-lazyload/blob/master/dist/js/libs.js

I'd feel better if this dependency was more explicit!

**Comment by daemon1981** [comment]
The dependency is explicit in the bower file https://github.com/francetv/ftv-angular-lazyload/blob/master/bower.json

**Comment by daemon1981** [comment]
Should we explicit for jquery as well ;)

**Comment by daemon1981** [comment]
https://github.com/francetv/ftv-angular-lazyload/blob/master/dist/js/libs.js is only used for the demo, we will remove it from the dist

**Comment by gmetais** [comment]
Oh sorry I forgot about bower and only checked package.json :) I'm closing!

**Comment by daemon1981** [comment]
@FloValence added a link to the lazyload project in the readme file ;)

Thanks for the remark @gmetais !

**Comment by FloValence** [comment]
FYI I updated the README to redirect to the Lazyload
https://github.com/francetv/ftv-angular-lazyload/commit/b986a048e1a94461e3418c2318f0b14b6f661f5c

**Comment by gmetais** [comment]
👍
